// Seed data synchronized from BD Consola Enjoy - central
window.INITIAL_DATA = [
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_001",
    "tarea_nombre": "Reunión DOM",
    "tarea_descripcion": "Reunión con DOM. El director de obras se mostró bastante entusiasmado con el nuevo proyecto y manifestó su disponibilidad para aprobar los permisos necesarios en el menor tiempo posible. Consultado sobre los temas ambientales, a su juicio las aprobaciones ya tramitadas para el proyecto original son válidos para solicitar permiso para este nuevo Proyecto",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-06-25",
    "fecha_legacy": "2026-06-25",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-06-25",
    "fecha_fin_real": "2026-06-25"
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_002",
    "tarea_nombre": "Compra galpón",
    "tarea_descripcion": "A la espera de la definición de la compra del galpón para generar expediente de permiso.",
    "tarea_responsable": "APE",
    "tarea_estado": "detenida",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_003",
    "tarea_nombre": "Visita terreno galpón",
    "tarea_descripcion": "Se realiza visita a terreno con ticket plus y proveedor de galpón para revisar ubicación del galpón y logística de acopio y montaje.",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-23",
    "fecha_legacy": "2026-07-23",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-23",
    "fecha_fin_real": "2026-07-23"
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_004",
    "tarea_nombre": "Envío información Cenit",
    "tarea_descripcion": "Se acuerda enviar información del actual Cenit: presentación a municipalidad, informe acústico y estudio de clima. Se hace la salvedad que el Cenit se diseñó como casino y no como salón de espectáculos. (enviada 24-jul)",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_005",
    "tarea_nombre": "Reunión Ticket Plus Veldeman",
    "tarea_descripcion": "Ticket Plus se reunirá la próxima semana con Veldeman para definir proyecto final, sus dimensiones y layout interior para la capacidad que se requiere.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_006",
    "tarea_nombre": "Reunión proyecto AA&BB",
    "tarea_descripcion": "Se acuerda con Ticket Plus realizar reunión para revisar ideas de proyecto de AA&BB y generar un master plan. Ticket Plus está evaluando la alternativa que los locatarios sean los que financien el proyecto",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_001",
    "tarea_nombre": "Aprobación presupuesto oficinas",
    "tarea_descripcion": "Se aprueba presupuesto por remodelación de oficinas piso 2 y 3 a bajo costo (966 UF – Plazo 5 semanas), considerando:\nReparación de cielos e iluminación nueva (reparación de filtraciones)\nPintura de todos los muros\nReconstruir las oficinas privadas que se habían eliminado (4)",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-06-09",
    "fecha_legacy": "2026-06-09",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-06-09",
    "fecha_fin_real": "2026-06-09"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_002",
    "tarea_nombre": "Generación PEP remodelación",
    "tarea_descripcion": "Se generar PEP para cargar la remodelación",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-06-19",
    "fecha_legacy": "2026-06-19",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-06-19",
    "fecha_fin_real": "2026-06-19"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_003",
    "tarea_nombre": "Ajuste PEP para OC",
    "tarea_descripcion": "Se ajustan PEP para generar OC",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-06-24",
    "fecha_legacy": "2026-06-24",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-06-24",
    "fecha_fin_real": "2026-06-24"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_004",
    "tarea_nombre": "Emisión OC",
    "tarea_descripcion": "Se emite orden de compra",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-06-25",
    "fecha_legacy": "2026-06-25",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-06-25",
    "fecha_fin_real": "2026-06-25"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_005",
    "tarea_nombre": "Envío contrato firma",
    "tarea_descripcion": "Se envía a través de DEC contrato para la firma",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-02",
    "fecha_legacy": "2026-07-02",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-02",
    "fecha_fin_real": "2026-07-02"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_006",
    "tarea_nombre": "Envío factura anticipo",
    "tarea_descripcion": "Se envía factura por anticipo a finanzas para pago y posterior inicio de obras",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-02",
    "fecha_legacy": "2026-07-02",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-02",
    "fecha_fin_real": "2026-07-02"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_007",
    "tarea_nombre": "Contrato firmado",
    "tarea_descripcion": "Fiscalía envía contrato firmado",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-08",
    "fecha_legacy": "2026-07-08",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-08",
    "fecha_fin_real": "2026-07-08"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_008",
    "tarea_nombre": "Confirmación pago anticipo",
    "tarea_descripcion": "Finanzas confirma pago de anticipo para el lunes 13-jul.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-10",
    "fecha_legacy": "2026-07-10",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-10",
    "fecha_inicio_real": "2026-07-10",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_009",
    "tarea_nombre": "Coordinación inicio obras",
    "tarea_descripcion": "Se contacta a la constructora para coordinar inicio de obras (fecha estimada lunes 20-jul)",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-13",
    "fecha_legacy": "2026-07-13",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-13",
    "fecha_fin_real": "2026-07-13"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_010",
    "tarea_nombre": "Reunión coordinación obras",
    "tarea_descripcion": "Se realiza reunión de coordinación con constructora, personas, mantención y prevención de riesgo para revisar algunos detalles antes del inicio de obras.",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-15",
    "fecha_legacy": "2026-07-15",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-15",
    "fecha_fin_real": "2026-07-15"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_011",
    "tarea_nombre": "Inicio obras piso 3",
    "tarea_descripcion": "Se acuerda como inicio de obras comenzando por el piso 3",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-22",
    "fecha_fin_real": "2026-07-22"
  },
  {
    "proyecto_id": "2026_RI019",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "REMODELACION OFICINA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI019_012",
    "tarea_nombre": "Revisión presupuestos",
    "tarea_descripcion": "Se realiza reunión para revisar presupuesto de mobiliario y presupuesto eléctrico de la habilitación. Se aprueba proyecto eléctrico y se solicita hablar con la empresa Ohiffice para ver una rebaja al presupuesto y poder adjudicarlo.",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-23",
    "fecha_legacy": "2026-07-23",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-27",
    "fecha_fin_real": "2026-07-23"
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_001",
    "tarea_nombre": "Evaluación nuevas iniciativas",
    "tarea_descripcion": "Unidad solicita ayuda en la evaluación de nuevas iniciativas\nAmpliación TGM exterior\nCortaviento Boulevard\nAmpliación terrazas Boulevard hotel",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-06-17",
    "fecha_legacy": "2026-06-17",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-06-17",
    "fecha_inicio_real": "2026-06-17",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_002",
    "tarea_nombre": "Levantamiento terreno alternativas",
    "tarea_descripcion": "levantamiento en terreno para las diferentes alternativas.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-06-24",
    "fecha_legacy": "2026-06-24",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-06-24",
    "fecha_inicio_real": "2026-06-24",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_003",
    "tarea_nombre": "Alternativas ampliación",
    "tarea_descripcion": "Se está trabajando en las diferentes alternativas para los proyectos de ampliación del TGM exterior y ampliación terraza del Boulevard",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-10",
    "fecha_legacy": "2026-07-10",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-10",
    "fecha_inicio_real": "2026-07-10",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_004",
    "tarea_nombre": "Visita propuesta Salón Cenit",
    "tarea_descripcion": "Se realiza visita a la unidad donde se solicita analizar una propuesta para tener mayor cantidad de posiciones en Salón Cenit",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-14",
    "fecha_legacy": "2026-07-14",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-14",
    "fecha_inicio_real": "2026-07-14",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_005",
    "tarea_nombre": "Propuestas ampliación TGM",
    "tarea_descripcion": "Se presenta avance con propuestas de ampliación de TGM fumadores actualizadas y valorizadas. Se acuerda independizar las 4 etapas para poder evaluarlas por separado y se define preliminarmente abordar la etapa 4 en una versión menor como 1ra prioridadGG solicita desarrollar más diseño de cortaviento para bajar el costo de manera sustancial, usando materiales económicos.",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-22",
    "fecha_inicio_real": "2026-07-22",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_006",
    "tarea_nombre": "Alternativas montaje Cenit",
    "tarea_descripcion": "Se presentan alternativas de montaje para el Cenit con la ubicación actual del escenario y dos más modificación ubicación.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_007",
    "tarea_nombre": "Revisión layout posiciones",
    "tarea_descripcion": "Se acuerda hacer una revisión final del layout de posiciones y pedir revisión al área respectiva de la unidad.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI020",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "NUEVAS INICIATIVAS",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI020_008",
    "tarea_nombre": "Plano actualizado MKT",
    "tarea_descripcion": "Se presenta plano actualizado a MKT de la unidad y se envía a revisión.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Alejandra Pérez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-22",
    "fecha_fin_real": "2026-07-22"
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_001",
    "tarea_nombre": "Recepción final TGM",
    "tarea_descripcion": "TGM exterior construido entre dic 23 y jul 25, donde quedo pendiente la recepción final de las obras",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "si",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_002",
    "tarea_nombre": "Documentos expediente DOM",
    "tarea_descripcion": "Para ingresar el expediente a la DOM faltan los siguientes documentos:\nPlan de seguridad a Bomberos (pagado a la espera de entrega)\nCarta a la DOM informando constructora e ITO (pendiente firma de la alcaldesa)",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_003",
    "tarea_nombre": "Fiscalización Seremi terraza",
    "tarea_descripcion": "Seremi fiscaliza terraza Salón Americano dejando acta con observaciones",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-14",
    "fecha_legacy": "2026-07-14",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-14",
    "fecha_fin_real": "2026-07-14"
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_004",
    "tarea_nombre": "Permiso DOM pendiente",
    "tarea_descripcion": "No contamos con el permiso de DOM recepcionado.",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_005",
    "tarea_nombre": "Ceniceros accesos",
    "tarea_descripcion": "Refiere existen ceniceros en cada asiento, pero no de pie en cada acceso, para personal que circula en sala. (se instalan en presencia del inspector)",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_006",
    "tarea_nombre": "Espacio abierto techumbre",
    "tarea_descripcion": "No se considera espacio abierto, teniendo techumbre. o en su defecto si techumbre no puede contar con paredes. (50% de la instalación y/o espacio abierto)",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_007",
    "tarea_nombre": "Actualización informe sanitario",
    "tarea_descripcion": "refiere que no se considera una actualización del informe sanitario DS 10/10 por las modificaciones realizadas y lo solicita en acta.",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_008",
    "tarea_nombre": "Ingreso descargos acta",
    "tarea_descripcion": "Se debe ingresar los descargo al acta de observaciones por plataforma 22-jul Se consigue plazo adicional para ingresar descargos",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-20",
    "fecha_legacy": "2026-07-20",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-20",
    "fecha_fin_real": "2026-07-20"
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_009",
    "tarea_nombre": "Solicitud antecedentes DOM",
    "tarea_descripcion": "se termina de solicitar por transparencia antecedentes no disponibles en la DOM.",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-22",
    "fecha_inicio_real": "2026-07-22",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_010",
    "tarea_nombre": "Envío descargos técnicos",
    "tarea_descripcion": "Se envía documento con descargos técnicos asociados al diseño del recinto.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-22",
    "fecha_fin_real": "2026-07-22"
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_011",
    "tarea_nombre": "Revisión expediente RF",
    "tarea_descripcion": "Unidad solicita avanzar con revisión de expediente de RF a la espera de carta de designación. Se enviará a la revisora una vez que llegue el certificado de Bomberos.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-23",
    "fecha_legacy": "2026-07-23",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-23",
    "fecha_inicio_real": "2026-07-23",
    "fecha_fin_proy": "2026-07-28",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2023_VI010",
    "unidad_nombre": "Enjoy Viña",
    "proyecto_nombre": "RECEPCIÓN SALÓN AMERICANO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2023_VI010_012",
    "tarea_nombre": "Ingreso descargos plataforma",
    "tarea_descripcion": "Se deben ingresar descargos por plataforma digital",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Rodrigo Borquez",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-24",
    "fecha_legacy": "2026-07-24",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-24",
    "fecha_fin_real": "2026-07-24"
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_001",
    "tarea_nombre": "Fiscalización modificaciones casino",
    "tarea_descripcion": "En dic 2024 DOM fiscalizó el casino detectando que habían modificaciones que no tenían permiso de obras",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "si",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_002",
    "tarea_nombre": "Solicitud permiso obra menor",
    "tarea_descripcion": "Se ingresó la solicitud de permiso de obra menor para resolver observaciones del casino.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-01-27",
    "fecha_legacy": "2026-01-27",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-01-27",
    "fecha_fin_real": "2026-01-27"
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_003",
    "tarea_nombre": "Aprobación modificaciones casino",
    "tarea_descripcion": "DOM aprobó modificaciones de casino y envió pago de derechos.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-04-10",
    "fecha_legacy": "2026-04-10",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-04-10",
    "fecha_fin_real": "2026-04-10"
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_004",
    "tarea_nombre": "Expediente recepción final",
    "tarea_descripcion": "Pendiente ingreso de expediente de recepción final, para lo cual falta aclarar quien está autorizado para firmar la solicitud de Recepción Final ante la Dirección de Obras Municipales",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-27",
    "fecha_legacy": "",
    "con_alerta": "si",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_005",
    "tarea_nombre": "Consulta representantes firma",
    "tarea_descripcion": "Se envía mail a P. Ocariz consultando por representantes con autorización para firma de expediente de recepción",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-06",
    "fecha_legacy": "2026-07-06",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-06",
    "fecha_inicio_real": "2026-07-06",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_006",
    "tarea_nombre": "Espera respuesta firma",
    "tarea_descripcion": "Aun no se recibe respuesta",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-10",
    "fecha_legacy": "2026-07-10",
    "con_alerta": "si",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-10",
    "fecha_fin_real": "2026-07-10"
  },
  {
    "proyecto_id": "2025_PU018",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "REGULARIZACIÓN CASINO",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU018_007",
    "tarea_nombre": "Seguimiento firmante expediente",
    "tarea_descripcion": "Aún no se recibe respuesta sobre firmante de expediente de Recepción Final en representación del propietario. Se enviará correo dando seguimiento.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-24",
    "fecha_legacy": "2026-07-24",
    "con_alerta": "si",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-24",
    "fecha_fin_real": "2026-07-24"
  },
  {
    "proyecto_id": "2025_PU019",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "TRASPASO A MONEDA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU019_001",
    "tarea_nombre": "Visita Moneda escalas",
    "tarea_descripcion": "Moneda realiza visita al hotel donde solicitó revisar escalas de evacuación y una propuesta de nuevas ubicaciones.",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-10",
    "fecha_legacy": "2026-07-10",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-10",
    "fecha_inicio_real": "2026-07-10",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2025_PU019",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "TRASPASO A MONEDA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU019_002",
    "tarea_nombre": "Solicitud repositorio inmuebles",
    "tarea_descripcion": "Arquitecto de Moneda solicita nuevamente repositorio ccn información de los inmuebles.",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-20",
    "fecha_legacy": "2026-07-20",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-20",
    "fecha_fin_real": "2026-07-20"
  },
  {
    "proyecto_id": "2025_PU019",
    "unidad_nombre": "Enjoy Pucón",
    "proyecto_nombre": "TRASPASO A MONEDA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2025_PU019_003",
    "tarea_nombre": "Envío repositorio",
    "tarea_descripcion": "Se envía repositorio",
    "tarea_responsable": "FHL",
    "tarea_estado": "terminada",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-22",
    "fecha_legacy": "2026-07-22",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2026-07-22",
    "fecha_fin_real": "2026-07-22"
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_001",
    "tarea_nombre": "Oficio DOM OVO Beach",
    "tarea_descripcion": "La unidad envía oficio recibido de la DOM por fiscalización de OVO Beach donde solicita regularizar las obras en un plazo máximo de 30 días.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2025-10-03",
    "fecha_legacy": "2025-10-03",
    "con_alerta": "si",
    "fecha_inicio_proy": "2025-10-03",
    "fecha_inicio_real": "2025-10-03",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_002",
    "tarea_nombre": "Ingreso expediente OVO Beach",
    "tarea_descripcion": "Se ingresa expediente de regularización de OVO beach a la DOM digital",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2025-10-20",
    "fecha_legacy": "2025-10-20",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2025-10-20",
    "fecha_fin_real": "2025-10-20"
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_003",
    "tarea_nombre": "Rechazo expediente DOM",
    "tarea_descripcion": "Se recibe oficio de la DOM rechazando el expediente de permios",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2025-11-21",
    "fecha_legacy": "2025-11-21",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2025-11-21",
    "fecha_fin_real": "2025-11-21"
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_004",
    "tarea_nombre": "Reingreso expediente OVO Beach",
    "tarea_descripcion": "se reingresa expediente de regularización de OVO Beach.",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2025-12-17",
    "fecha_legacy": "2025-12-17",
    "con_alerta": "no",
    "fecha_inicio_proy": "",
    "fecha_inicio_real": "",
    "fecha_fin_proy": "2025-12-17",
    "fecha_fin_real": "2025-12-17"
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_005",
    "tarea_nombre": "Nuevo rechazo expediente",
    "tarea_descripcion": "llega nuevo rechazo al expediente",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-01-08",
    "fecha_legacy": "2026-01-08",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-01-08",
    "fecha_inicio_real": "2026-01-08",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_006",
    "tarea_nombre": "Envío costos regularización",
    "tarea_descripcion": "Se envía a Unidad costos asociados a la regularización del OVO Beach para aprobación (aproximado 9 millones)",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-02-10",
    "fecha_legacy": "2026-02-10",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-02-10",
    "fecha_inicio_real": "2026-02-10",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_007",
    "tarea_nombre": "Fiscalización OVO Beach",
    "tarea_descripcion": "DOM, patentes y gobernación marítima vuelve a fiscalizar Ovo beach, enviando acta de observaciones y otorgando plazo máximo de 30 días para su regularización",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-01",
    "fecha_legacy": "2026-07-01",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-01",
    "fecha_inicio_real": "2026-07-01",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_008",
    "tarea_nombre": "Aprobación costos OVO Beach",
    "tarea_descripcion": "Se envía a Unidad mail con costos asociados a la regularización del OVO beach para aprobación.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-06",
    "fecha_legacy": "2026-07-06",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-06",
    "fecha_inicio_real": "2026-07-06",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_CQ020",
    "unidad_nombre": "Enjoy Coquimbo",
    "proyecto_nombre": "OVO BEACH",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_CQ020_009",
    "tarea_nombre": "Daños temporales OVO Beach",
    "tarea_descripcion": "Edificaciones sufren daños profundos por temporal. Regularización queda sujeta a proceso de rehabilitación del espacio.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "GG Unidad",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-17",
    "fecha_legacy": "2026-07-17",
    "con_alerta": "si",
    "fecha_inicio_proy": "2026-07-17",
    "fecha_inicio_real": "2026-07-17",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_TR001",
    "unidad_nombre": "Enjoy Transversales",
    "proyecto_nombre": "MANTENCIÓN",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_TR001_001",
    "tarea_nombre": "Comité mantención avances",
    "tarea_descripcion": "Se realiza comité de mantención donde se presentan avances. Se solicita no adjudicar Rinconada hasta contar con más ofertas.",
    "tarea_responsable": "JPB",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Vicente Alamo",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-14",
    "fecha_legacy": "2026-07-14",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-14",
    "fecha_inicio_real": "2026-07-14",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_TR001",
    "unidad_nombre": "Enjoy Transversales",
    "proyecto_nombre": "MANTENCIÓN",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_TR001_002",
    "tarea_nombre": "Búsqueda proveedores",
    "tarea_descripcion": "Se solicita a cadena de suministros ayuda buscando proveedores. Se recibe respuesta indicando que ellos no cuentan con datos de algún otro proveedor local. La unidad buscará alguna alternativa en la zona",
    "tarea_responsable": "FHL",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Nicolás Cerda",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-20",
    "fecha_legacy": "2026-07-20",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-20",
    "fecha_inicio_real": "2026-07-20",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_TR001",
    "unidad_nombre": "Enjoy Transversales",
    "proyecto_nombre": "MANTENCIÓN",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_TR001_003",
    "tarea_nombre": "Reunión avance Rinconada",
    "tarea_descripcion": "Se realiza reunión con Rinconada para revisar cómo van avanzando con los siguientes temas:\nConversaciones con empresa de mantención de clima actual por deficiencia en los servicios y pagos atrasados\nCotización con otras empresas por servicios de mantención y plan piloto de para renovar equipos de clima del hotel\nDefinición de capex, próxima semana se realizara reunión para revisión.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Nicolás Cerda",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-21",
    "fecha_legacy": "2026-07-21",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-21",
    "fecha_inicio_real": "2026-07-21",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_TR001",
    "unidad_nombre": "Enjoy Transversales",
    "proyecto_nombre": "MANTENCIÓN",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_TR001_004",
    "tarea_nombre": "Reunión piscinas Pucón",
    "tarea_descripcion": "Se realiza reunión con Pucón por tema de piscinas, se acuerda evaluar posibles costos adicionales a solicitar por el proveedor con la oferta más atractiva para hacer reparaciones, buscando no alterar ahorros encontrados.",
    "tarea_responsable": "APE",
    "tarea_estado": "en desarrollo",
    "tarea_contraparte": "Gabriel Contreras",
    "tarea_pct": "",
    "tarea_fecha_creacion": "2026-07-23",
    "fecha_legacy": "2026-07-23",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-23",
    "fecha_inicio_real": "2026-07-23",
    "fecha_fin_proy": "",
    "fecha_fin_real": ""
  },
  {
    "proyecto_id": "2026_RI017",
    "unidad_nombre": "Enjoy Rinconada",
    "proyecto_nombre": "ARENA",
    "proyecto_estado": "en desarrollo",
    "proyecto_descripcion": "",
    "tarea_id": "2026_RI017_007",
    "tarea_nombre": "Reunión DOM",
    "tarea_descripcion": "Reunión con DOM",
    "tarea_responsable": "APE",
    "tarea_estado": "terminada",
    "tarea_contraparte": "DOM",
    "tarea_pct": "100",
    "tarea_fecha_creacion": "2026-07-01",
    "fecha_legacy": "2026-07-01",
    "con_alerta": "no",
    "fecha_inicio_proy": "2026-07-01",
    "fecha_inicio_real": "2026-07-01",
    "fecha_fin_proy": "2026-07-24",
    "fecha_fin_real": "2026-07-24"
  }
];
